version: '3.1'

services:
  api:
    image: dksxogh9023218/palettee-server:latest
    container_name: test-green
    environment:
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8081
    ports:
      - '8081:8081'