version: '3.1'

services:
  api:
    image: dksxogh9023218/palettee-server:latest
    container_name: test-blue
    environment:
      - LANG=ko_KR.UTF-8
      - HTTP_PORT=8080
    ports:
      - '8080:8081'