logging:
  level:
    com.palettee: debug
    web: debug
    sql: debug
  slack:
    webhook-uri: https://hooks.slack.com/services/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

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 8112
    url: jdbc:mysql://localhost:3306/final_project

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        jdbc:
          time_zone: UTC
        format_sql: true   # SQL 포맷팅을 활성화

  # OAuth redirect URL for local dev
  security:
    oauth2:
      client:
        registration:
          google:
            redirect-uri: http://localhost:8080/login/oauth2/code/google

          github:
            redirect-uri: http://localhost:8080/login/oauth2/code/github

oauth-success-redirect-uri: /token/issue

redis:
  host: localhost
  port: 6379
  password:

LOG_DIR: ./logs

environment: local