spring:
  profiles:
    active: local
    include: secret

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false


# Swagger -> localhost:8080/api-test
springdoc:
  swagger-ui:
    path: /api-test
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method

sse:
  timeout: 3600000 # 1시간

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "health, info, prometheus"
    jmx:
      exposure:
        exclude: "*"

  endpoint:
    health:
      enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
