logging:
  level:
    com.palettee: debug
    web: debug
    sql: debug

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: an902318
    url: jdbc:mysql://localhost:3306/palette

  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
    hibernate:
      ddl-auto: create

redis:
  host: localhost
  port: 6379
  password: